name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    name: Build & Test Spring Boot Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend
        working-directory: Email_Reply_Generator
        run: mvn clean package -DskipTests

      - name: Run tests
        working-directory: Email_Reply_Generator
        run: mvn test

  frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: Email_Reply_Generator_React
        run: npm install

      - name: Build frontend
        working-directory: Email_Reply_Generator_React
        run: npm run build

  extension:
    name: Validate Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Lint manifest.json
        run: |
          jq . Email_Reply_Generator_Ext/manifest.json > /dev/null
